### PR TITLE
code coverage and some niceties..

### PR DESCRIPTION
**Pull request by yonderblue**
can you believe niceties is a real word?

### CODE REVIEW

**Comment by yonderblue** [comment]
@nubs of course there is no rush on this, but just FYI it all runs in linux just fine for you :P

**Comment by nubs** [comment]
I would much rather see the SharpCover stuff pulled in as a git submodule or similar, and built as part of the build process.

**Comment by yonderblue** [comment]
so you would want nunit and mongo should to be submodules as well?

**Comment by nubs** [comment]
What I want is for the installation of them to be repeatable AND easily changeable.  The second point is what makes either submodules or package managers attractive.  If there's a new version out, I want to be able to update the version easily in a way that others can easily understand and repeat.

Uploading new dlls is not easily understood - what compile options were used to create those dlls; were the dlls downloaded from somewhere and if so where; does this include the full collection of libraries/utilities that the dependency has, or was just one dll pulled out of the whole bundle; what is the definitive source for these libraries?

Instead, I strongly recommend, when possible, having dependencies be bundled/installed/built from a definitive source via simple repeatable methods.  Package managers are a great way of doing this, because a public repository can be a terrific source of record for versioned packages and the installation of the libraries can be very simple and very complete (executables, documentation, etc. are generally included).

In the absence of package managers, a simple build process for the dependency downloading the source material from some defined source by repeatable code works as well.  If the dependency's source can be downloaded via git, a git submodule helps make it easy to maintain, otherwise you're probably having to do a curl call (or something equivalent for windows) to download a tarball, etc.

**Comment by yonderblue** [comment]
What is easier than dropping a prebuilt dll into a lib folder? Not to mention the dlls in here _are_ versioned, and is managed code not machine specific and subject to funky compiler options etc. Replacing with an updated version is as simple as downloading a dll, which just isn't up yet.

I don't think you would recommend i include mongo in the same way as you suggest yet there isn't a difference in how the project uses them.

Not to mention building all your dependencies is is not common in hardly any system. .dll, .rpm, .deb, .pkg, .jar, .so, .a etc etc all binary.

**Comment by nubs** [comment]
Dropping a prebuilt dll may be easy, but it does not give anyone but the one who did it a clue about where that dll came from other than the file name, which could be misleading.

I would recommend that mongo is installed via https://www.nuget.org/packages/mongocsharpdriver in the same we install our php dependencies via pear/composer.

.rpm and .deb definitely include the type of dependency management I'm referring to.  The .src.rpm and IIRC the .deb file contain the dependency package names which can be downloaded and built separately.  They are more sophisticated systems in that pre-built binaries are available to reduce installation time and client-side dependencies (don't need gcc installed to install packages, etc), but those binaries can be re-generated, tweaked, etc. very simply and with identical results.

.so and .dll files have a similar mechanism by allowing dynamic linking.  They don't have to include their dependencies with them, those dependencies can just be referenced by name and installed and managed separately.

If nuget is available for the dependencies we need, why not use it?

**Comment by yonderblue** [comment]
I have no problem sticking in nuget, just in a next pull request as it's out of scope for this one. Nuget had problems on Linux a while ago but I'll check it again.

**Comment by yonderblue** [comment]
I have no problem with a dependency manager to pull things from an authoritative source, i was responding to your comments about source building and/or managed dlls being subject to the machine they were generated on, which they aren't. For me personally, managed assemblies have plenty of information in them to get a new one shall i need and don't cause me headaches, but the _nicety_ of a dependency manager is fine with me :P, next pull request.

**Pull request merged**
